name: Deploy Lambda

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deplopy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: npm install
        working-directory: ./lambda
        env:
          CI: true
        run: |
          npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ vars.AWS_TARGET_REGION }}
          role-session-name: "GitHubActions-DeployLambda"

      - name: Deploy Lambda
        run: |
          npx ncc build index.ts 
          zip -j deploy.zip ./dist/*
          # aws cli - deploy code