name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deplopy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: npm install
        working-directory: ./lambda
        env:
          CI: true
        run: |
          npm ci